### ISSUE TITLE
Hey please check out the mica discord repo issues please ;)

### ISSUE THREAD

**Issue by StaticGamerYT-India** [Get0457/WinWrapper#1]
I thought that the issue i posted in mica discord repo didnt draw your attention so i made another issue post here 
sorry if it is irritating :)

**Comment by GetGet99** [comment]
Hi... Sorry for not responding... I don't usually check GitHub issues. For faster communication, I'm normally active on [Developer Sanctuary Discord Server on `#gets-project`](https://discord.gg/EkMuza2T). You don't have to join, but I normally can respond to issues faster on that server.
